
MEMORY
{
   program (RX) : ORIGIN = 0, LENGTH = 0x0020000
   data (!RX) : ORIGIN = 0x79400, LENGTH = 0x6C00
}
ENTRY(__start)
SECTIONS
{
  . = 0x0;
  .text : {
     /* the __start symbol has to come at address zero. */
     *crt0.o(.text*)
     _ctors_start = .;
     _init_array_start = .;
     KEEP(SORT(*.init_array))
     _ctors_end = .;
     _init_array_end = .;
     _dtors_start = .;
     _dtors_end = .;
     *(.text*)
  } > program
  .data : {
     *(.data*)
     *(.rodata*)
  } > data
  .comment : {
     *(.comment*)
  }
  .symtab : {
     *(.symtab)
  }
  .shstrtab : {
     *(.shstrtab)
  }
  .strtab : {
     *(.strtab)
  }

. = 0x70000;
_sp_start_value_DM_stack = .;
. += 0x400; /* stack */
/* No tile with memory exists to the south. */
. = 0x40000;
. += 0x10000;
/* No tile with memory exists to the west. */
. = 0x50000;
. += 0x10000;
. = 0x64400;
fifo_2_cons_buff_0 = .;
. += 0x1000;
. = 0x65400;
fifo_2_cons_buff_1 = .;
. += 0x1000;
. = 0x66400;
pipe_c_0_src_buff_0 = .;
. += 0x1000;
. = 0x67400;
pipe_c_0_src_buff_1 = .;
. += 0x1000;
. = 0x60400;
pipe_b_0_dst_cons_buff_0 = .;
. += 0x2000;
. = 0x62400;
_anonymous2 = .;
. += 0x2000;
. = 0x70400;
fifo_4_buff_0 = .;
. += 0x2000;
. = 0x72400;
fifo_4_buff_1 = .;
. += 0x2000;
. = 0x76400;
pipe_c_0_dst_cons_buff_0 = .;
. += 0x1000;
. = 0x77400;
pipe_c_0_dst_cons_buff_1 = .;
. += 0x1000;
. = 0x74400;
_anonymous0 = .;
. += 0x2000;
. = 0x78400;
_anonymous1 = .;
. += 0x1000;
  .bss : { *(.bss*) } > data
}
PROVIDE(main = core_0_2);
