
MEMORY
{
   program (RX) : ORIGIN = 0, LENGTH = 0x0020000
   data (!RX) : ORIGIN = 0x75604, LENGTH = 0xA9FC
}
ENTRY(__start)
SECTIONS
{
  . = 0x0;
  .text : {
     /* the __start symbol has to come at address zero. */
     *crt0.o(.text*)
     _ctors_start = .;
     _init_array_start = .;
     KEEP(SORT(*.init_array))
     _ctors_end = .;
     _init_array_end = .;
     _dtors_start = .;
     _dtors_end = .;
     *(.text*)
  } > program
  .data : {
     *(.data*)
     *(.rodata*)
  } > data
  .comment : {
     *(.comment*)
  }
  .symtab : {
     *(.symtab)
  }
  .shstrtab : {
     *(.shstrtab)
  }
  .strtab : {
     *(.strtab)
  }

. = 0x70000;
_sp_start_value_DM_stack = .;
. += 0x400; /* stack */
. = 0x40400;
fifo_12_buff_0 = .;
. += 0x1000;
. = 0x41400;
fifo_12_buff_1 = .;
. += 0x1000;
. = 0x43400;
fifo_7_0_cons_buff_0 = .;
. += 0x800;
. = 0x43C00;
fifo_7_0_cons_buff_1 = .;
. += 0x800;
. = 0x44400;
fifo_3_1_cons_buff_0 = .;
. += 0x800;
. = 0x44C00;
fifo_3_1_cons_buff_1 = .;
. += 0x800;
. = 0x42400;
_anonymous18 = .;
. += 0x1000;
. = 0x45400;
_anonymous19 = .;
. += 0x200;
. = 0x45600;
_anonymous20 = .;
. += 0x4;
. = 0x53400;
fifo_6_1_cons_buff_0 = .;
. += 0x800;
. = 0x53C00;
fifo_6_1_cons_buff_1 = .;
. += 0x800;
. = 0x54400;
fifo_0_0_cons_buff_0 = .;
. += 0x800;
. = 0x54C00;
fifo_0_0_cons_buff_1 = .;
. += 0x800;
. = 0x50400;
pipe_0_0_1_buff_0 = .;
. += 0x1000;
. = 0x51400;
pipe_0_0_1_buff_1 = .;
. += 0x1000;
. = 0x52400;
_anonymous6 = .;
. += 0x1000;
. = 0x55400;
_anonymous7 = .;
. += 0x200;
. = 0x55600;
_anonymous8 = .;
. += 0x4;
. = 0x73400;
fifo_5_1_cons_buff_0 = .;
. += 0x800;
. = 0x73C00;
fifo_5_1_cons_buff_1 = .;
. += 0x800;
. = 0x74400;
fifo_2_1_cons_buff_0 = .;
. += 0x800;
. = 0x74C00;
fifo_2_1_cons_buff_1 = .;
. += 0x800;
. = 0x70400;
pipe_0_1_0_buff_0 = .;
. += 0x1000;
. = 0x71400;
pipe_0_1_0_buff_1 = .;
. += 0x1000;
. = 0x72400;
_anonymous9 = .;
. += 0x1000;
. = 0x75400;
_anonymous10 = .;
. += 0x200;
. = 0x75600;
_anonymous11 = .;
. += 0x4;
  .bss : { *(.bss*) } > data
}
INPUT(external0.o)
PROVIDE(main = core_2_3);
