
MEMORY
{
   program (RX) : ORIGIN = 0, LENGTH = 0x0020000
   data (!RX) : ORIGIN = 0x75604, LENGTH = 0xA9FC
}
ENTRY(__start)
SECTIONS
{
  . = 0x0;
  .text : {
     /* the __start symbol has to come at address zero. */
     *crt0.o(.text*)
     _ctors_start = .;
     _init_array_start = .;
     KEEP(SORT(*.init_array))
     _ctors_end = .;
     _init_array_end = .;
     _dtors_start = .;
     _dtors_end = .;
     *(.text*)
  } > program
  .data : {
     *(.data*)
     *(.rodata*)
  } > data
  .comment : {
     *(.comment*)
  }
  .symtab : {
     *(.symtab)
  }
  .shstrtab : {
     *(.shstrtab)
  }
  .strtab : {
     *(.strtab)
  }

. = 0x70000;
_sp_start_value_DM_stack = .;
. += 0x400; /* stack */
/* No tile with memory exists to the south. */
. = 0x40000;
. += 0x10000;
. = 0x50400;
fifo_10_buff_0 = .;
. += 0x1000;
. = 0x51400;
fifo_10_buff_1 = .;
. += 0x1000;
. = 0x53400;
fifo_7_1_cons_buff_0 = .;
. += 0x800;
. = 0x53C00;
fifo_7_1_cons_buff_1 = .;
. += 0x800;
. = 0x54400;
fifo_1_0_cons_buff_0 = .;
. += 0x800;
. = 0x54C00;
fifo_1_0_cons_buff_1 = .;
. += 0x800;
. = 0x52400;
_anonymous3 = .;
. += 0x1000;
. = 0x55400;
_anonymous4 = .;
. += 0x200;
. = 0x55600;
_anonymous5 = .;
. += 0x4;
. = 0x63400;
fifo_6_1_cons_buff_0 = .;
. += 0x800;
. = 0x63C00;
fifo_6_1_cons_buff_1 = .;
. += 0x800;
. = 0x64400;
fifo_0_0_cons_buff_0 = .;
. += 0x800;
. = 0x64C00;
fifo_0_0_cons_buff_1 = .;
. += 0x800;
. = 0x60400;
pipe_0_0_1_buff_0 = .;
. += 0x1000;
. = 0x61400;
pipe_0_0_1_buff_1 = .;
. += 0x1000;
. = 0x62400;
_anonymous6 = .;
. += 0x1000;
. = 0x65400;
_anonymous7 = .;
. += 0x200;
. = 0x65600;
_anonymous8 = .;
. += 0x4;
. = 0x70400;
fifo_11_buff_0 = .;
. += 0x1000;
. = 0x71400;
fifo_11_buff_1 = .;
. += 0x1000;
. = 0x73400;
fifo_8_0_cons_buff_0 = .;
. += 0x800;
. = 0x73C00;
fifo_8_0_cons_buff_1 = .;
. += 0x800;
. = 0x74400;
fifo_1_1_cons_buff_0 = .;
. += 0x800;
. = 0x74C00;
fifo_1_1_cons_buff_1 = .;
. += 0x800;
. = 0x72400;
_anonymous15 = .;
. += 0x1000;
. = 0x75400;
_anonymous16 = .;
. += 0x200;
. = 0x75600;
_anonymous17 = .;
. += 0x4;
  .bss : { *(.bss*) } > data
}
PROVIDE(main = core_1_2);
