
// External kernels generated by Allo
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <type_traits>
#include <aie_api/aie.hpp>
#include "aie2/zero.cc"

extern "C" {

void fill_zeros_i32_32_32_vector(int *A) {
  zero_vectorized<int, 32, 32>(A);
}

} // extern "C"

